crawler:
  keywords: ["cat", "dog", "cute cat", "cute dog"]
  labels: ["cat", "dog", "cat", "dog"]
  start_date: [2020, 1, 1]
  end_date: [2020, 8, 1]
  max_num: 100
download:
  resize_max_size: [600, 600]
make_clf_dataset:
  ratio: [0.7, 0.15, 0.15]
  label2index: null
train_clf:
  preprocess:
    rescale_scale: "1./127.5"
    rescale_offset: -1.0
    img_size: [224, 224]
  augment:
    RandomFlip:
      mode: horizontal
    RandomRotation:
      factor: 0.
  optimizer:
    name: Adam
    params:
      learning_rate: 0.001
  model:
    base_model:
      name: mobilenet_v2
    top_model:
      dropout_rate: 0.2