crawler:
  keywords: ["cat", "dog", "cute cat", "cute dog"]
  labels: ["cat", "dog", "cat", "dog"]
  start_date: [2020, 1, 1]
  end_date: [2020, 8, 1]
mlflow:
  experiment_name: crawling_images
  tracking_uri: http://localhost:5001