preprocess:
  input_data_csv:
    run_id: d7d40014e60a4ba5b7a3ed17647e014b
    path: crawler_result.csv
  input_images:
    run_id: d7d40014e60a4ba5b7a3ed17647e014b
    path: images
  ratio: [0.7, 0.15, 0.15]
  img_size: [299, 299]
mlflow:
  experiment_name: preprocess_images
  tracking_uri: http://localhost:5000