name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_pypi:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
        echo ::set-output name=PACKAGE_VERSION::$(cat pyproject.toml | grep "^version =" | tr -d "version = \"")
    - name: Check version
      run: |
        echo "v${PACKAGE_VERSION}" && \
        echo "${TAG_VERSION}" && \
        test "v${PACKAGE_VERSION}" = "${TAG_VERSION}"
      env:
        TAG_VERSION: ${{ steps.get_version.outputs.TAG_VERSION }}
        PACKAGE_VERSION: ${{ steps.get_version.outputs.PACKAGE_VERSION }}
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Publish pypi
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry publish --build